// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Twldogl9YU3toSZmARwBiDvWyObno_s',
    appId: '1:962945026868:web:4f23b3ec0a5a7524087361',
    messagingSenderId: '962945026868',
    projectId: 'flutter-login01-7ca61',
    authDomain: 'flutter-login01-7ca61.firebaseapp.com',
    storageBucket: 'flutter-login01-7ca61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVEXMfDSxwRhW74QruqfGbb_ePFj_UEZM',
    appId: '1:962945026868:android:940f7780fa32c35e087361',
    messagingSenderId: '962945026868',
    projectId: 'flutter-login01-7ca61',
    storageBucket: 'flutter-login01-7ca61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX35NaVZexATY1nji5fA6G_VjlOJ9Zcjw',
    appId: '1:962945026868:ios:41e3db861b6baacd087361',
    messagingSenderId: '962945026868',
    projectId: 'flutter-login01-7ca61',
    storageBucket: 'flutter-login01-7ca61.appspot.com',
    iosClientId: '962945026868-m5vc1ivlgp42n87gb25bcsl20q3lkqb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginUi01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX35NaVZexATY1nji5fA6G_VjlOJ9Zcjw',
    appId: '1:962945026868:ios:144a65f1a0aff6bc087361',
    messagingSenderId: '962945026868',
    projectId: 'flutter-login01-7ca61',
    storageBucket: 'flutter-login01-7ca61.appspot.com',
    iosClientId: '962945026868-6rre079o8sivqu7qkbhiv4gf3v65v5oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginUi01.RunnerTests',
  );
}
